name: cplay-fatpack

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  cplay:
    env:
      # some plugins still needs this to run their tests...
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 0
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 0

    runs-on: ubuntu-latest

    steps:
      # no need to checkout
      #- uses: actions/checkout@v2

      - name: perl -V
        run: perl -V

      - name: '%Config'
        run: perl -MConfig -MTest::More -E 'note explain \%Config'

      - name: perl '-V:install.*'
        run: perl '-V:install.*'

      - name: install cplay
        run: |
          curl -fsSL --compressed http://get.cplay.us > cplay
          chmod +x cplay
          ./cplay --version

      # sudo ./cplay from-tarball -d https://github.com/${{ github.repository }}/archive/${{ github.sha }}.tar.gz
      - name: cplay from-tarball A1z-Html
        run: |
          sudo ./cplay from-tarball -d https://github.com/pause-play/A1z-Html/archive/p5.tar.gz
