name: cplay-build

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  build:
    env:
      # some plugins still needs this to run their tests...
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 0
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 0
      # would be better to find a different module without deps
      CPLAY_MODULE: 'Acme::Alien::DontPanic'
      CPLAY_DISTRO: 'Acme-Alien-DontPanic'

    runs-on: ubuntu-latest

    steps:
      # no need to checkout
      #- uses: actions/checkout@v2

      - name: perl -V
        run: perl -V

      uses: perl-actions/install-cpm@v1.0

      # install module using cpm
      - name: "cpm ${{ env.CPLAY_MODULE }} & deps"
        run: |
          sudo cpm install -g --show-build-log-on-failure ${{ env.CPLAY_MODULE }}
          perl -m${{ env.CPLAY_MODULE }} -e1

      - name: remove ${{ env.CPLAY_MODULE }}
        run: |
          sudo rm -f $(perldoc -lm ${{ env.CPLAY_MODULE }})

      - name: install cplay
        run: |
          curl -L https://git.io/cplay | sudo perl - self-install
          which cplay
          cplay --version

      - name: cplay from-tarball ${{ env.CPLAY_DISTRO }}
        run: |
          sudo cplay from-tarball -d https://github.com/pause-play/${{ env.CPLAY_DISTRO }}/archive/p5.tar.gz

      - name: check module is installed
        run: |
          perl -m${{ env.CPLAY_MODULE }} -e1